name: Release for MacOS
on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to release'
        required: true
        default: 'v0.1.1'

jobs:
  macos:
    runs-on: macos-latest
    env:
      PKG_CONFIG_PATH: /usr/local/lib/pkgconfig:$PKG_CONFIG_PATH
    steps:
      - uses: actions/checkout@v2
      - name: Install macfuse
        run: |
          brew install macfuse
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: aarch64-apple-darwin
          profile: minimal
          default: true
      - name: Cache cargo build
        uses: Swatinem/rust-cache@v1
      - name: Build wheels - x86_64
        uses: PyO3/maturin-action@v1
        with:
          target: x86_64-apple-darwin
          args: --release --out target/dist --strip
      - name: Upload wheels
        uses: actions/upload-artifact@v2
        with:
          name: wheels
          path: target/dist
          if-no-files-found: error
      - name: Upload binary artifacts
        uses: actions/upload-artifact@v2
        with:
          name: apple-darwin-bin
          path: target/x86_64-apple-darwin/release/alist-fuse
          if-no-files-found: error
      - name: Archive binary
        run: |
          cd target/x86_64-apple-darwin/release
          tar czvf alist-fuse-${{ github.event.inputs.tag }}.apple-darwin.tar.gz alist-fuse
          shasum -a 256 alist-fuse-${{ github.event.inputs.tag }}.apple-darwin.tar.gz > alist-fuse-${{ github.event.inputs.tag }}.apple-darwin.tar.gz.sha256
          cd -
      - name: Upload binary to GitHub Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/x86_64-apple-darwin/release/alist-fuse-${{ github.event.inputs.tag }}.apple-darwin.tar.gz
          file_glob: false
          overwrite: true
          tag: "refs/tags/${{ github.event.inputs.tag }}"